// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGwymEvtL6bosNEKC1EMO0fdhpGPiJpyU',
    appId: '1:743802210249:web:a70e810f32d8bcd1bf4a18',
    messagingSenderId: '743802210249',
    projectId: 'girlai2',
    authDomain: 'girlai2.firebaseapp.com',
    storageBucket: 'girlai2.firebasestorage.app',
    measurementId: 'G-YNQ4LGV6CR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcCy66h7D_qZTWhRhqSiZLeqnVX0bjK4g',
    appId: '1:743802210249:android:6216945189c7ef97bf4a18',
    messagingSenderId: '743802210249',
    projectId: 'girlai2',
    storageBucket: 'girlai2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb44k-oZcCBL4sNHKB1YI4UF8mg0AUDtE',
    appId: '1:743802210249:ios:b56d0b442727aad1bf4a18',
    messagingSenderId: '743802210249',
    projectId: 'girlai2',
    storageBucket: 'girlai2.firebasestorage.app',
    iosBundleId: 'com.mikeyb.girlai2',
  );
}
