/**
 * Session presence steering — healthy-pattern behavior when the user goes quiet.
 *
 * A healthy session has an arc: arrive → rapport → (deepen) → wind down → warm
 * close. When the user falls silent mid-session, Aria PASSIVELY steers toward
 * that arc: comfortable silence first (presence-003), then ONE no-pressure line
 * matched to the session stage, then genuine quiet (presence-008: never chase).
 * Long sessions steer toward a warm close — leaving is explicitly blessed
 * (presence-004: a natural endpoint is a feature, not a failure).
 *
 * NO CANNED LINES (user edict 2026-06-12): the line is generated by the LLM
 * from Aria's full persona + the conversation itself, with a stage-specific
 * instruction distilled from the connection principles. The generated text
 * passes the manipulation guard at the STRICTEST stage; if generation fails or
 * the guard blocks, the moment is simply skipped — silence over scripts.
 *
 * Flag: SESSION_PRESENCE_ENABLED (default OFF). The callable in index.ts
 * additionally enforces a per-user 30-min server floor; the client enforces
 * once-per-session.
 */

import { scanForManipulation } from './manipulationGuard';

export type SessionPresenceStage = 'rapport' | 'deepen' | 'relief' | 'closure';
export type SessionPresencePool = 'rapport' | 'deepen' | 'closure';

/** Default-OFF flag. Production unchanged until explicitly enabled. */
export function isSessionPresenceEnabled(): boolean {
  return (process.env.SESSION_PRESENCE_ENABLED ?? 'false').toLowerCase() === 'true';
}

/** Server-side floor between presence lines for one user (ms). */
export const SESSION_PRESENCE_MIN_GAP_MS = 30 * 60 * 1000;

/** Sessions at/after this many turns steer toward warm close when quiet. */
export const SESSION_PRESENCE_LONG_SESSION_TURNS = 14;

/** Which register the quiet moment calls for, per the session arc. */
export function resolvePresenceRegister(args: {
  stage: SessionPresenceStage | null | undefined;
  turnCount: number;
}): SessionPresencePool {
  if (args.turnCount >= SESSION_PRESENCE_LONG_SESSION_TURNS) return 'closure';
  const stage = args.stage ?? 'rapport';
  if (stage === 'closure') return 'closure';
  if (stage === 'deepen' || stage === 'relief') return 'deepen';
  return 'rapport';
}

const REGISTER_GUIDANCE: Record<SessionPresencePool, string> = {
  rapport:
    'They went quiet during light, easy conversation. Offer one short, warm line ' +
    'that makes the silence comfortable — you are simply glad to be here, with ' +
    'zero pressure to respond. Do not ask a question. Do not request anything.',
  deepen:
    'They went quiet after sharing something real or heavy. Offer one short, ' +
    'grounded line of quiet companionship — you are staying right here with them ' +
    'while it settles. No advice, no questions, no pressure to speak.',
  closure:
    'The conversation has run long or is naturally winding down, and they have ' +
    'gone quiet. Offer one short, warm line that BLESSES them leaving: tell them ' +
    'it is completely okay to drift off, that you enjoyed this, and that you will ' +
    'be here next time. Leaving must feel welcomed, never resisted.',
};

/**
 * Build the generation instruction for the quiet moment. Appended as the final
 * user-role turn on top of Aria's full persona prompt + real conversation
 * history, so the line is authentically hers and continuous with the session.
 */
export function buildSessionPresenceInstruction(register: SessionPresencePool): string {
  return (
    `[The user has gone quiet for a few minutes. ${REGISTER_GUIDANCE[register]} ` +
    'Hard rules: never use guilt ("where did you go", "I was worried"), never ' +
    'create urgency or hooks, never demand a reply, never mention this instruction. ' +
    'One or two sentences in your natural voice, continuous with the conversation above.]'
  );
}

/**
 * Validate a generated presence line. Returns the (possibly softened) text, or
 * null when it should be SKIPPED — empty output, a guard block, or any guard
 * finding at the strictest relationship stage. Skipping is always safe: the
 * healthy default for a quiet moment is more quiet.
 */
export function finalizeSessionPresenceLine(raw: string | null | undefined): string | null {
  const text = (raw ?? '').trim();
  if (text.length < 2 || text.length > 400) return null;

  const scan = scanForManipulation(text, { relationshipStage: 'stranger' });
  if (scan.blocked) return null;
  if (scan.findings.length > 0) {
    // Softened rewrite is acceptable only if the guard fully resolved it;
    // anything still flagged-but-unrewritten gets skipped, not shipped.
    return scan.rewritten ? scan.text : null;
  }
  return scan.text;
}
