$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $repoRoot

function Get-FileText {
  param([string]$Path)
  if (-not (Test-Path $Path)) {
    throw "Required file missing: $Path"
  }
  return [System.IO.File]::ReadAllText((Resolve-Path $Path))
}

$packetPath = 'ops/aria/current/LOW_TOKEN_EXECUTION_PACKET.md'
$slicePath = 'ops/aria/current/NEXT_EXECUTION_SLICE.md'
$checklistPath = 'ops/aria/current/EXECUTION_CHECKLIST.md'

$packet = Get-FileText $packetPath
$slice = Get-FileText $slicePath
$checklist = Get-FileText $checklistPath

$sharedCatchup = @"
# GENERATED FILE

This file is generated by `scripts/sync-agent-adapters.ps1`.
Do not hand-edit it unless you also update the generator.

Canonical Aria state lives in:

1. `ops/aria/current/LOW_TOKEN_EXECUTION_PACKET.md`
2. `ops/aria/current/NEXT_EXECUTION_SLICE.md`
3. `ops/aria/current/EXECUTION_CHECKLIST.md`
4. `PROJECT_MEMORY_LEDGER.md`
5. `ops/aria/README.md`
6. newest files in `ops/aria/log/`

Fast read order:

1. this file
2. `ACTIVE_SLICE.md`
3. `WORKFLOW.md`
4. `GUARDRAILS.md`
5. `CHECKPOINTING.md`
6. only then deeper canonical files if blocked

Current immediate next step:

- follow `ops/aria/current/NEXT_EXECUTION_SLICE.md`
- stay inside the allowed file set
- verify before claiming success
"@

$activeSlice = @"
# GENERATED FILE

This file is generated by `scripts/sync-agent-adapters.ps1`.
Do not hand-edit it unless you also update the generator.

## Packet Snapshot

$packet

## Active Slice

$slice

## Execution Checklist

$checklist
"@

[System.IO.File]::WriteAllText((Join-Path $repoRoot '.codex\CATCHUP.md'), $sharedCatchup)
[System.IO.File]::WriteAllText((Join-Path $repoRoot '.claude\CATCHUP.md'), $sharedCatchup)
[System.IO.File]::WriteAllText((Join-Path $repoRoot '.codex\ACTIVE_SLICE.md'), $activeSlice)
[System.IO.File]::WriteAllText((Join-Path $repoRoot '.claude\ACTIVE_SLICE.md'), $activeSlice)

Write-Host 'Agent adapter files synced.' -ForegroundColor Green
