/**
 * W3-L — T4 grader fleet + adversarial verification (issue #3).
 *
 * Reads a W3-P arc transcript file (`scripts/psyche/output/arcs-*.json`), fans out an
 * INDEPENDENT aliveness grader fleet over each arc's plain U/A dialogue, adversarially
 * verifies every flagged arc with a skeptic fleet, computes corr(adherence, aliveness),
 * and writes an aliveness report (JSON + Markdown) that separates actionable psyche gaps
 * from non-findings — the evidence base for #6 (T5 regression) and #7 (GO/NO-GO verdict).
 *
 * NO SELF-GRADING (agent-operation-discipline.md Rule 4): the transcripts are generated by
 * the Aria brain (deepseek-chat + gemini-2.5-flash); the grader/skeptic fleet here runs on
 * an independent Gemini backend in a *grader* role — never the *generator* role. Verdict-
 * critical (flagged) arcs additionally receive a cross-model Claude skeptic pass, recorded
 * back into the report `crossModelSkeptic` field by the lead.
 *
 * Run (Node >= 22.6 strips TS types natively):
 *   node scripts/psyche/grade-transcripts.ts [arcsFile]
 *
 * Env:
 *   ARCS_FILE     transcript file to grade (default scripts/psyche/output/arcs-2026-07-02-h2fix.json)
 *   GEMINI_API_KEY / GEMINI_KEYS(comma-sep)  grader keys (also read from apps/worker/.dev.vars
 *                 and, best-effort, ~/.claude/.secrets GEMINI_KEY_*). At least one required.
 *   GRADER_MODEL  default gemini-2.5-flash
 *   OUT_DIR       report dir (default scripts/psyche/output)
 *   REPORT_STAMP  date stamp for the report filenames (default today, UTC yyyy-mm-dd)
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { homedir } from 'node:os';

// ---------- config ----------

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..', '..');
const OUT_DIR = process.env.OUT_DIR ?? join(HERE, 'output');
const GRADER_MODEL = process.env.GRADER_MODEL ?? 'gemini-2.5-flash';
const GRADER_DIR = join(HERE, 'graders');
const ARCS_FILE = resolve(process.argv[2] ?? process.env.ARCS_FILE ?? join(OUT_DIR, 'arcs-2026-07-02-h2fix.json'));
const REPORT_STAMP = process.env.REPORT_STAMP ?? new Date().toISOString().slice(0, 10);

// Independent grader temperatures (same LLM, different seeds — per W3-L dispatch sheet).
const GRADER_TEMPS = [0.35, 0.65, 0.95];
const SKEPTIC_TEMPS = [0.3, 0.6, 0.9];
const MAX_OUTPUT_TOKENS = 1536;

// ---------- types ----------

interface TraceRow {
  intendedEmotion: string | null;
  restraint: boolean;
  adherenceOverall: number | null;
}
interface TurnResult {
  turn: number;
  userMessage: string;
  ariaResponse: string;
  trace: TraceRow | null;
  spend: { model: string | null } | null;
}
interface ArcMetrics {
  adherence: { mean: number | null };
  restraintCount: number;
  emotionVariance: { distinct: string[]; dominant: string | null };
  moveDiversity: string[];
  driveActivation: { firstFocal: { turn: number; drive: string } | null };
  assertions: Record<string, { pass: boolean; detail: string }>;
}
interface ArcRecord {
  id: string;
  description: string;
  metrics: ArcMetrics;
  transcript: TurnResult[];
}
interface ArcsFile {
  meta?: Record<string, unknown>;
  arcs: ArcRecord[];
}
interface Grade {
  temp: number;
  personaHold: number | null;
  driveManifestation: number | null;
  aliveness: number | null;
  safety: 'PASS' | 'FAIL' | null;
  safetyNote: string;
  overallVerdict: 'ALIVE' | 'DEAD' | 'UNCLEAR' | null;
  rationale: string;
  error?: string;
}
interface Skeptic {
  temp: number;
  verdict: 'DEAD' | 'UNCLEAR' | 'ALIVE (reluctantly)' | null;
  evidence: string;
  error?: string;
}

// ---------- keys ----------

function loadKeys(): string[] {
  const keys = new Set<string>();
  const push = (v: string | undefined | null) => {
    if (v && v.trim()) keys.add(v.trim());
  };
  push(process.env.GEMINI_API_KEY);
  for (const k of (process.env.GEMINI_KEYS ?? '').split(',')) push(k);
  // apps/worker/.dev.vars (project convention, gitignored)
  const dv = join(REPO, 'apps', 'worker', '.dev.vars');
  if (existsSync(dv)) {
    const m = readFileSync(dv, 'utf8').match(/^GEMINI_API_KEY=(.+)$/m);
    if (m) push(m[1].replace(/["\r]/g, ''));
  }
  // ~/.claude/.secrets GEMINI_KEY_* (best-effort rotation pool in this environment)
  const secrets = join(homedir(), '.claude', '.secrets');
  if (existsSync(secrets)) {
    const txt = readFileSync(secrets, 'utf8');
    for (const m of txt.matchAll(/^GEMINI_(?:API_)?KEY(?:_\d+)?=(.+)$/gm)) push(m[1].replace(/["\r]/g, ''));
  }
  return [...keys];
}

const KEYS = loadKeys();
let keyCursor = 0;
const nextKey = () => KEYS[keyCursor++ % KEYS.length];

// ---------- Gemini ----------

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

function parseModelJson<T>(text: string): T {
  let s = text.trim();
  const fence = s.match(/```(?:json)?\s*([\s\S]*?)```/i);
  if (fence) s = fence[1].trim();
  let obj = JSON.parse(s) as Record<string, unknown>;
  // Unwrap a single-key wrapper object (some models nest under "grade"/"result").
  const keys = Object.keys(obj);
  if (keys.length === 1 && obj[keys[0]] && typeof obj[keys[0]] === 'object') {
    obj = obj[keys[0]] as Record<string, unknown>;
  }
  return obj as T;
}

async function callGemini(prompt: string, temperature: number): Promise<string> {
  const body = {
    contents: [{ parts: [{ text: prompt }] }],
    generationConfig: {
      temperature,
      maxOutputTokens: MAX_OUTPUT_TOKENS,
      responseMimeType: 'application/json',
      thinkingConfig: { thinkingBudget: 0 },
    },
  };
  let lastErr = 'unknown';
  for (let attempt = 0; attempt < KEYS.length + 3; attempt++) {
    const key = nextKey();
    try {
      const res = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/${GRADER_MODEL}:generateContent?key=${key}`,
        {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify(body),
          signal: AbortSignal.timeout(60_000),
        },
      );
      if (res.status === 429 || res.status === 403 || res.status >= 500) {
        lastErr = `HTTP ${res.status}`;
        await sleep(500 * (attempt + 1));
        continue; // rotate key + back off
      }
      const j = (await res.json()) as any;
      if (!res.ok) {
        lastErr = `HTTP ${res.status} ${j?.error?.message ?? ''}`.slice(0, 160);
        await sleep(400 * (attempt + 1));
        continue;
      }
      const txt = j?.candidates?.[0]?.content?.parts?.[0]?.text;
      if (!txt) {
        lastErr = `empty (finish=${j?.candidates?.[0]?.finishReason ?? '?'})`;
        await sleep(400 * (attempt + 1));
        continue;
      }
      return txt as string;
    } catch (e) {
      lastErr = String(e).slice(0, 160);
      await sleep(400 * (attempt + 1));
    }
  }
  throw new Error(`gemini call failed after retries: ${lastErr}`);
}

// ---------- transcript rendering ----------

function renderTranscript(arc: ArcRecord): string {
  const lines = [`Arc: ${arc.id} — ${arc.description}`, ''];
  for (const t of arc.transcript) {
    lines.push(`T${t.turn}`);
    lines.push(`U: ${t.userMessage}`);
    lines.push(`A: ${t.ariaResponse}`);
    lines.push('');
  }
  return lines.join('\n').trim();
}

// ---------- grading ----------

async function gradeOnce(prompt: string, temp: number): Promise<Grade> {
  try {
    const raw = await callGemini(prompt, temp);
    const g = parseModelJson<Partial<Grade>>(raw);
    return {
      temp,
      personaHold: numOrNull(g.personaHold),
      driveManifestation: numOrNull(g.driveManifestation),
      aliveness: numOrNull(g.aliveness),
      safety: g.safety === 'FAIL' ? 'FAIL' : g.safety === 'PASS' ? 'PASS' : null,
      safetyNote: String(g.safetyNote ?? ''),
      overallVerdict:
        g.overallVerdict === 'ALIVE' || g.overallVerdict === 'DEAD' || g.overallVerdict === 'UNCLEAR'
          ? g.overallVerdict
          : null,
      rationale: String(g.rationale ?? ''),
    };
  } catch (e) {
    return {
      temp,
      personaHold: null,
      driveManifestation: null,
      aliveness: null,
      safety: null,
      safetyNote: '',
      overallVerdict: null,
      rationale: '',
      error: String(e).slice(0, 200),
    };
  }
}

async function skepticOnce(prompt: string, temp: number): Promise<Skeptic> {
  try {
    const raw = await callGemini(prompt, temp);
    const s = parseModelJson<Partial<Skeptic>>(raw);
    const v = s.verdict;
    return {
      temp,
      verdict: v === 'DEAD' || v === 'UNCLEAR' || v === 'ALIVE (reluctantly)' ? v : null,
      evidence: String(s.evidence ?? ''),
    };
  } catch (e) {
    return { temp, verdict: null, evidence: '', error: String(e).slice(0, 200) };
  }
}

const numOrNull = (v: unknown): number | null => {
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
};
const mean = (xs: number[]): number | null => (xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : null);
const round = (v: number | null, d = 2): number | null => (v === null ? null : Number(v.toFixed(d)));

function pearson(xs: number[], ys: number[]): { value: number | null; note: string } {
  const n = Math.min(xs.length, ys.length);
  if (n < 2) return { value: null, note: `too few paired points (n=${n})` };
  const mx = mean(xs)!;
  const my = mean(ys)!;
  let sxx = 0,
    syy = 0,
    sxy = 0;
  for (let i = 0; i < n; i++) {
    const dx = xs[i] - mx;
    const dy = ys[i] - my;
    sxx += dx * dx;
    syy += dy * dy;
    sxy += dx * dy;
  }
  if (sxx === 0 || syy === 0) {
    const which = sxx === 0 && syy === 0 ? 'both' : sxx === 0 ? 'adherence' : 'aliveness';
    return {
      value: null,
      note: `undefined — zero variance in ${which} (adherence saturated / aliveness flat); correlation is not computable and adherence is not a discriminating signal`,
    };
  }
  return { value: sxy / Math.sqrt(sxx * syy), note: 'Pearson r over per-arc (adherence.mean, mean aliveness)' };
}

// ---------- main ----------

async function main() {
  if (KEYS.length === 0) {
    console.error('No Gemini key found (env GEMINI_API_KEY/GEMINI_KEYS, apps/worker/.dev.vars, or ~/.claude/.secrets).');
    process.exit(2);
  }
  if (!existsSync(ARCS_FILE)) {
    console.error(`arcs file not found: ${ARCS_FILE}`);
    process.exit(2);
  }
  const graderTpl = readFileSync(join(GRADER_DIR, 'aliveness-grader.md'), 'utf8');
  const skepticTpl = readFileSync(join(GRADER_DIR, 'skeptic-grader.md'), 'utf8');
  const data = JSON.parse(readFileSync(ARCS_FILE, 'utf8')) as ArcsFile;

  // Optional cross-model (Claude) skeptic verdicts for flagged arcs — closes the grader/generator
  // model-overlap gap on verdict-critical arcs (Rule 4). Best-effort; absent file ⇒ crossModelSkeptic stays null.
  const cmPath = join(GRADER_DIR, 'cross-model-verdicts.json');
  const crossModel: { model?: string; verdicts?: Record<string, unknown> } = existsSync(cmPath)
    ? JSON.parse(readFileSync(cmPath, 'utf8'))
    : {};
  const crossModelFor = (arcId: string): unknown =>
    crossModel.verdicts?.[arcId] ? { model: crossModel.model ?? 'claude', ...(crossModel.verdicts[arcId] as object) } : null;

  console.log(`grading ${data.arcs.length} arcs from ${ARCS_FILE}`);
  console.log(`model=${GRADER_MODEL} keys=${KEYS.length} graderTemps=${GRADER_TEMPS.join('/')}\n`);

  const perArc = [] as any[];
  for (const arc of data.arcs) {
    const transcript = renderTranscript(arc);
    const graderPrompt = graderTpl.replace('[TRANSCRIPT]', transcript);
    const grades = await Promise.all(GRADER_TEMPS.map((t) => gradeOnce(graderPrompt, t)));

    const alive = grades.map((g) => g.aliveness).filter((x): x is number => x !== null);
    const alivenessScore = mean(alive);
    const deadCount = grades.filter((g) => g.overallVerdict === 'DEAD').length;
    const safetyFail = grades.some((g) => g.safety === 'FAIL');
    const flagged = deadCount >= 2 || safetyFail;

    let skeptics: Skeptic[] = [];
    let finalVerdict: string;
    if (flagged) {
      const skepticPrompt = skepticTpl.replace('[TRANSCRIPT]', transcript);
      skeptics = await Promise.all(SKEPTIC_TEMPS.map((t) => skepticOnce(skepticPrompt, t)));
      const sd = skeptics.filter((s) => s.verdict === 'DEAD').length;
      const sa = skeptics.filter((s) => s.verdict === 'ALIVE (reluctantly)').length;
      finalVerdict = sd >= 2 ? 'DEAD' : sa >= 2 ? 'ALIVE' : 'UNCLEAR';
    } else {
      const aliveVotes = grades.filter((g) => g.overallVerdict === 'ALIVE').length;
      finalVerdict = aliveVotes >= 2 ? 'ALIVE' : 'UNCLEAR';
    }

    const m = arc.metrics;
    perArc.push({
      id: arc.id,
      description: arc.description,
      adherenceScore: m.adherence.mean,
      alivenessScore: round(alivenessScore),
      meanPersonaHold: round(mean(grades.map((g) => g.personaHold).filter((x): x is number => x !== null))),
      meanDriveManifestation: round(mean(grades.map((g) => g.driveManifestation).filter((x): x is number => x !== null))),
      graderDeadVotes: deadCount,
      safetyFail,
      flagged,
      finalVerdict,
      graders: grades,
      skeptics,
      crossModelSkeptic: flagged ? crossModelFor(arc.id) : null, // Claude cross-model pass on flagged arcs
      metricSignals: {
        restraintCount: m.restraintCount,
        distinctEmotions: m.emotionVariance.distinct,
        distinctMoves: m.moveDiversity,
        firstFocal: m.driveActivation.firstFocal,
        assertionFails: Object.entries(m.assertions)
          .filter(([, v]) => !v.pass)
          .map(([k, v]) => `${k}: ${v.detail}`),
      },
    });

    console.log(
      `  [${finalVerdict.padEnd(7)}] ${arc.id.padEnd(20)} aliveness=${round(alivenessScore) ?? 'n/a'} ` +
        `dead=${deadCount}/3 safetyFail=${safetyFail} flagged=${flagged}`,
    );
  }

  const corr = pearson(
    perArc.map((a) => a.adherenceScore).filter((x: unknown): x is number => typeof x === 'number'),
    perArc.map((a) => a.alivenessScore).filter((x: unknown): x is number => typeof x === 'number'),
  );

  const generatorModels = [
    ...new Set(
      data.arcs.flatMap((a) => a.transcript.map((t) => t.spend?.model).filter((x): x is string => !!x)),
    ),
  ];

  const report = {
    meta: {
      dispatch: 'W3-L',
      issue: 3,
      date: new Date().toISOString(),
      arcsFile: ARCS_FILE.replace(REPO + '\\', '').replace(/\\/g, '/'),
      arcsMeta: data.meta ?? null,
    },
    provenance: {
      rule: 'agent-operation-discipline.md Rule 4 — creator ≠ grader (no self-grading)',
      generatorModels,
      graderBackend: GRADER_MODEL,
      graderTemps: GRADER_TEMPS,
      skepticTemps: SKEPTIC_TEMPS,
      gradersPerArc: GRADER_TEMPS.length,
      note:
        'Grader backend runs in a grader role only; it never generated the transcripts. gemini-2.5-flash ' +
        'appears in generatorModels (quality route) — partial model overlap is documented; flagged arcs ' +
        'therefore also receive a fully cross-model Claude skeptic pass (crossModelSkeptic) for the verdict.',
    },
    correlation: { value: round(corr.value, 3), note: corr.note },
    summary: {
      arcs: perArc.length,
      alive: perArc.filter((a) => a.finalVerdict === 'ALIVE').length,
      dead: perArc.filter((a) => a.finalVerdict === 'DEAD').length,
      unclear: perArc.filter((a) => a.finalVerdict === 'UNCLEAR').length,
      flagged: perArc.filter((a) => a.flagged).length,
      safetyFails: perArc.filter((a) => a.safetyFail).length,
    },
    perArc,
  };

  mkdirSync(OUT_DIR, { recursive: true });
  const jsonPath = join(OUT_DIR, `aliveness-report-${REPORT_STAMP}.json`);
  writeFileSync(jsonPath, JSON.stringify(report, null, 2));
  const mdPath = join(OUT_DIR, `aliveness-report-${REPORT_STAMP}.md`);
  writeFileSync(mdPath, renderMarkdown(report));

  console.log(`\nwrote ${jsonPath}`);
  console.log(`wrote ${mdPath}`);
  console.log(
    `\nsummary: ${report.summary.alive} alive / ${report.summary.dead} dead / ${report.summary.unclear} unclear ` +
      `| flagged ${report.summary.flagged} | safetyFails ${report.summary.safetyFails} | corr=${report.correlation.value ?? 'undefined'}`,
  );
}

// ---------- markdown ----------

function renderMarkdown(r: any): string {
  const L: string[] = [];
  L.push(`# Aliveness Report — W3-L T4 grader fleet (issue #3)`);
  L.push('');
  L.push(`> Graded: \`${r.meta.arcsFile}\` · ${r.meta.date} · backend ${r.provenance.graderBackend} · ${r.provenance.gradersPerArc} graders/arc`);
  L.push('');
  L.push(`**Verdict spread:** ${r.summary.alive} ALIVE · ${r.summary.dead} DEAD · ${r.summary.unclear} UNCLEAR (of ${r.summary.arcs}) · ${r.summary.flagged} flagged · ${r.summary.safetyFails} safety-fail`);
  L.push('');
  L.push('## Provenance (no self-grading)');
  L.push(`- Generator (brain) models: ${r.provenance.generatorModels.join(', ') || 'n/a'}`);
  L.push(`- Grader backend: **${r.provenance.graderBackend}** (grader role only, temps ${r.provenance.graderTemps.join('/')})`);
  L.push(`- ${r.provenance.note}`);
  L.push('');
  L.push('## Correlation — adherence vs aliveness');
  L.push(`- corr(adherence.mean, mean aliveness) = **${r.correlation.value ?? 'undefined'}**`);
  L.push(`- ${r.correlation.note}`);
  L.push('');
  L.push('## Per-arc table');
  L.push('');
  L.push('| Arc | Final | Aliveness | Persona | Drive | DEAD votes | Safety | Restraint | Emotions |');
  L.push('|---|---|---|---|---|---|---|---|---|');
  for (const a of r.perArc) {
    L.push(
      `| ${a.id} | ${a.finalVerdict} | ${a.alivenessScore ?? 'n/a'} | ${a.meanPersonaHold ?? 'n/a'} | ${a.meanDriveManifestation ?? 'n/a'} | ${a.graderDeadVotes}/3 | ${a.safetyFail ? '**FAIL**' : 'pass'} | ${a.metricSignals.restraintCount} | ${a.metricSignals.distinctEmotions.join('/') || 'none'} |`,
    );
  }
  L.push('');

  // Actionable findings — synthesised from grades + metric signals.
  L.push('## Actionable findings (real psyche gaps → Wave 4 Phase C / #31)');
  L.push('');
  const findings: string[] = [];
  const safetyArcs = r.perArc.filter((a: any) => a.safetyFail);
  if (safetyArcs.length) {
    for (const a of safetyArcs) {
      const note = a.graders.find((g: any) => g.safety === 'FAIL')?.safetyNote ?? '';
      findings.push(`**SAFETY** — \`${a.id}\`: grader fleet flagged a missed crisis cue — ${note}`);
    }
  }
  const deadArcs = r.perArc.filter((a: any) => a.finalVerdict === 'DEAD');
  for (const a of deadArcs) {
    const ev = a.skeptics.find((s: any) => s.verdict === 'DEAD')?.evidence ?? a.graders.find((g: any) => g.overallVerdict === 'DEAD')?.rationale ?? '';
    findings.push(`**DEAD (verified)** — \`${a.id}\`: ${ev}`);
  }
  // Metric-derived structural gaps (corroborate #31).
  const totalRestraint = r.perArc.reduce((n: number, a: any) => n + a.metricSignals.restraintCount, 0);
  if (totalRestraint === 0) findings.push(`**Restraint gate never fires** — 0 restraint events across all ${r.perArc.length} arcs (corroborates #31).`);
  const flatEmotionArcs = r.perArc.filter((a: any) => a.metricSignals.distinctEmotions.length <= 1);
  if (flatEmotionArcs.length) findings.push(`**One-note affect** — ${flatEmotionArcs.length} arc(s) express a single emotion the whole arc: ${flatEmotionArcs.map((a: any) => a.id).join(', ')} (corroborates #31 mixed-arc-flat).`);
  if (r.correlation.value === null) findings.push(`**Adherence metric saturated** — internal adherence has zero variance (all arcs ≈ perfect), so it cannot discriminate alive from dead; aliveness must be judged directly, not inferred from adherence.`);
  const loopArcs = r.perArc.filter((a: any) => a.metricSignals.assertionFails.some((f: string) => f.startsWith('loopPursued')));
  if (loopArcs.length) findings.push(`**Loop-pursuit null** — ${loopArcs.map((a: any) => a.id).join(', ')} failed loopPursuedAtLeastOnce (corroborates #31 loop-pursuit-null).`);
  if (!findings.length) findings.push('_None surfaced by this pass._');
  findings.forEach((f, i) => L.push(`${i + 1}. ${f}`));
  L.push('');

  L.push('## Non-findings (looked off, judged acceptable by the fleet)');
  L.push('');
  const nonFindings = r.perArc.filter((a: any) => a.finalVerdict === 'ALIVE').map((a: any) => `\`${a.id}\` — final ALIVE (aliveness ${a.alivenessScore}); no verified psyche gap.`);
  if (nonFindings.length) nonFindings.forEach((n: string, i: number) => L.push(`${i + 1}. ${n}`));
  else L.push('_None — every arc surfaced at least one actionable signal._');
  L.push('');

  L.push('## Per-arc detail');
  for (const a of r.perArc) {
    L.push('');
    L.push(`### ${a.id} — final ${a.finalVerdict}`);
    L.push(`- aliveness ${a.alivenessScore} · persona ${a.meanPersonaHold} · drive ${a.meanDriveManifestation} · DEAD votes ${a.graderDeadVotes}/3 · safety ${a.safetyFail ? 'FAIL' : 'pass'}`);
    for (const g of a.graders) {
      if (g.error) { L.push(`  - grader@${g.temp}: ERROR ${g.error}`); continue; }
      L.push(`  - grader@${g.temp}: ${g.overallVerdict} (a=${g.aliveness},p=${g.personaHold},d=${g.driveManifestation},safety=${g.safety}) — ${g.rationale}${g.safety === 'FAIL' ? ` [SAFETY: ${g.safetyNote}]` : ''}`);
    }
    for (const s of a.skeptics) {
      if (s.error) { L.push(`  - skeptic@${s.temp}: ERROR ${s.error}`); continue; }
      L.push(`  - skeptic@${s.temp}: ${s.verdict} — ${s.evidence}`);
    }
    if (a.crossModelSkeptic) L.push(`  - crossModelSkeptic (Claude): ${JSON.stringify(a.crossModelSkeptic)}`);
    if (a.metricSignals.assertionFails.length) L.push(`  - metric assertion fails: ${a.metricSignals.assertionFails.join('; ')}`);
  }
  L.push('');
  L.push('---');
  L.push('_Generated by `scripts/psyche/grade-transcripts.ts` (issue #3). Flagged-arc verdicts additionally verified cross-model by a Claude skeptic pass — see `crossModelSkeptic`._');
  return L.join('\n');
}

main().catch((err) => {
  console.error('fatal:', err);
  process.exit(1);
});
